---
- name: Check if Harbor is already installed
  community.kubernetes.helm_info:
    name: harbor
    namespace: harbor
  register: harbor_installed

- name: Add harbor repository to Helm
  community.kubernetes.helm_repository:
    name: harbor
    repo_url: http://{{ helm_repo_ip }}/harbor
    state: present
  when: harbor_installed.helm_info is undefined or harbor_installed.helm_info.resources | length == 0

- name: Install or Upgrade Harbor Helm chart
  community.kubernetes.helm:
    name: harbor
    chart_ref: harbor/harbor
    release_namespace: harbor
    create_namespace: true
    values: "{{ harbor_values | combine({'externalURL': item}) }}"
  loop: "{{ harbor_values.externalURLs }}"
  when: harbor_installed.helm_info is undefined or harbor_installed.helm_info.resources | length == 0

- name: Pause for 5 seconds
  pause:
    seconds: 5

- name: Wait for all harbor pods to be ready
  shell: >
    kubectl get pods -n harbor -o custom-columns=:status.phase --no-headers| grep operator | grep -v Running | grep -v Completed || true
  register: not_running_rook_pods
  until: not_running_rook_pods.stdout == ""
  retries: 20
  delay: 60
  become: true