---
# Kubernetes Cluster Basic Installation Playbook
# Usage: ansible-playbook -i inventory.ini site.yml

# Phase 1: System Preparation  
- name: System Preparation
  hosts: all
  become: yes
  serial: "100%"
  strategy: "{{ 'free' if (parallel_execution | default({})).system_preparation | default(1) == 0 else 'linear' }}"
  roles:
    - { role: common, tags: ['base', 'system'] }
    - { role: configure_sysctl, tags: ['base', 'system'] }
    - { role: configure_chrony, tags: ['base', 'time'] }
    - { role: configure_repo, tags: ['base', 'packages'] }
    - { role: install_os_package, tags: ['base', 'packages'] }
    - { role: install_containerd, tags: ['base', 'container'] }
    - { role: setup-docker-credentials, tags: ['docker-credentials'] }

# Phase 2: Kubernetes Installation
- name: Kubernetes Cluster Installation
  hosts: all
  become: yes
  serial: "100%"
  strategy: "{{ 'free' if (parallel_execution | default({})).kubernetes_installation | default(1) == 0 else 'linear' }}"
  roles:
    - { role: install_kubernetes, tags: ['kubernetes', 'cluster'] }

# Phase 3: Network Plugin Installation
- name: Network Plugin Setup
  hosts: masters
  become: yes
  roles:
    - { role: install_flannel, tags: ['kubernetes', 'networking'] }

# Phase 4: Optional Master Node Scheduling (if single node)
- name: Master Node Scheduling Setup
  hosts: masters
  become: yes
  roles:
    - { role: remove_master_taint, tags: ['kubernetes', 'scheduling'], when: allow_master_scheduling | default(false) }

# Phase 5: Certificate Extension (Optional)
- name: Extend Kubernetes Certificates to 10 Years
  hosts: masters
  become: yes
  roles:
    - { role: extend_k8s_certs, tags: ['kubernetes', 'certificates', 'k8s-certs'], when: extend_k8s_certificates | default(false) }

# Phase 6: CoreDNS Hosts Configuration (Optional)
- name: CoreDNS Hosts Configuration
  hosts: masters
  become: yes
  roles:
    - { role: configure_coredns_hosts, tags: ['coredns-hosts'], when: configure_coredns_hosts | default(false) }

# Phase 7: NFS Server Setup
- name: NFS Server Setup
  hosts: master1
  become: yes
  roles:
    - { role: nfs-server, tags: ['nfs'] }

# Phase 8: Harbor Project Setup (Final)
- name: Harbor Project Setup
  hosts: all
  become: yes
  roles:
    - { role: harbor-project-setup, tags: ['harbor-setup'] }
