---
- hosts: all
  roles:
#    - common
#    - configure_repo
#    - configure_sysctl
#    - install_OS_package
#    - install_docker
#    - install_kubernetes

- hosts: installs
  roles:
#    - install_flannel
#    - install_tools
#    - remove_master_taint
    - install_cert_manager
