---
- hosts: all
  roles:
#    - common
#    - configure_repo
#    - configure_sysctl
#    - install_os_package
#    - install_docker
#    - install_kubernetes

- hosts: installs
  roles:
#    - install_flannel
#    - install_tools
#    - remove_master_taint
#    - install_cert_manager
#    - install_rook_ceph
#    - install_istio
#    - install_metal_lb
#    - install_harbor
#    - install_prometheus
#    - install_ef # elastic & fluentd
#    - install_knative
#    - install_minio
    - install_argo
