---
- hosts: all
  roles:
    - common
    - configure_repo
#    - install_OS_package
#    - install_docker
#
#- hosts: installs
#    - install_tools
#
#- hosts: masters
#  roles:
#    - master
#
#- hosts: workers
#  roles:
#    - worker
