---
# Update Node IP Playbook
# 
# Kubernetes 설정 파일의 IP를 변경합니다.
# 주의: 이 플레이북은 파일만 변경합니다. IP 변경은 사용자가 직접 수행해야 합니다.
#
# 사용법:
#   ansible-playbook -i inventory.ini update-node-ip.yml \
#     -e 'old_ip=192.168.1.100' \
#     -e 'new_ip=192.168.1.200' \
#     --limit master1
#
# 변수:
#   old_ip: (필수) 변경 전 IP
#   new_ip: (선택) 변경 후 IP (기본값: ansible_host)
#   regenerate_certs: (선택) 인증서 재생성 여부

- name: Update Node IP Configuration
  hosts: masters
  become: yes
  gather_facts: yes
  
  roles:
    - role: update_node_ip
      tags:
        - update-ip
