---
- name: Configure repository for CentOS
  include_tasks: setup_centos_repo.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Configure repository for Ubuntu
  include_tasks: setup_ubuntu_repo.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Configure repository for Ubuntu
  include_tasks: setup_ubuntu_repo.yml
  when: ansible_facts['os_family'] == "Debian"
