---
- name: Configure Ubuntu sources list
  copy:
    content: |
      deb [trusted=yes] {{ repo_url.ubuntu }} ./
    dest: /etc/apt/sources.list

- name: Update and upgrade packages
  apt:
    update_cache: yes