---
- name: Install Docker and containerd (Ubuntu)
  apt:
    name:
      - docker-ce
      - containerd.io
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install Docker and containerd (CentOS)
  yum:
    name:
      - docker-ce
      - containerd.io
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Ensure Docker config directory exists
  file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: Ensure Docker service is enabled and running
  service:
    name: docker
    state: started
    enabled: true

- name: Check if GPU is installed
  shell: lspci | grep -i nvidia
  register: gpu_installed
  ignore_errors: true
  changed_when: false

- name: Set GPU fact
  set_fact:
    gpu_added: "{{ gpu_installed.rc == 0 }}"

- name: Configure Docker daemon
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  vars:
    gpu_added: "{{ gpu_added }}"
  notify: restart docker

- name: Ensure kubelet is enabled and running
  systemd:
    name: kubelet
    enabled: yes
    state: started
