---
# =============================================================================
# CLUSTER STATUS CHECK TASKS
# =============================================================================
# This role displays cluster status and information after installation
# =============================================================================

- name: Display cluster status
  shell: kubectl get nodes -o wide
  register: cluster_nodes
  
- name: Show cluster nodes status
  debug:
    var: cluster_nodes.stdout_lines

- name: Display cluster info
  shell: kubectl cluster-info
  register: cluster_info
  
- name: Show cluster information
  debug:
    var: cluster_info.stdout_lines

- name: Check pod status in all namespaces
  shell: kubectl get pods --all-namespaces
  register: all_pods
  
- name: Show all pods status
  debug:
    var: all_pods.stdout_lines

- name: Display cluster status completion
  debug:
    msg: "Cluster status check completed successfully on {{ inventory_hostname }}"