---

- name: Get all Helm releases
  command: helm list --all-namespaces -o json
  register: helm_releases
  changed_when: false
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"
  when: "'masters' in group_names"

- name: Uninstall all Helm releases
  command: helm uninstall {{ item.name }} -n {{ item.namespace }}
  loop: "{{ (helm_releases.stdout | from_json) }}"
  loop_control:
    label: "{{ item.name }}"
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"
  when: "'masters' in group_names"

#- name: Get list of all namespaces
#  shell: kubectl get ns -o jsonpath="{.items[*].metadata.name}" 
#  register: all_namespaces
#  changed_when: false
#  run_once: true
#  delegate_to: "{{ groups['masters'][0] }}"
#  when: "'masters' in group_names"
#
#- name: Delete namespaces used by Helm releases
#  command: kubectl delete ns {{ item }}
#  loop: "{{ (helm_releases.stdout | from_json) | map(attribute='namespace') | unique }}"
#  when: item in all_namespaces.stdout.split()
#  run_once: true
#  delegate_to: "{{ groups['masters'][0] }}"
#  when: "'masters' in group_names"

