---
- name: Render Corefile template to a temporary file
  template:
    src: templates/corefile.j2
    dest: /tmp/Corefile.yaml

- name: Create or update CoreDNS ConfigMap
  shell: kubectl apply -f /tmp/Corefile.yaml

- name: Restart CoreDNS deployment
  command: kubectl rollout restart deployment coredns -n kube-system
  register: rollout_result

- name: Display rollout status
  debug:
    msg: "{{ rollout_result.stdout }}"