---
- name: restart containerd
  service:
    name: containerd
    state: restarted
    enabled: yes

- name: restart buildkit
  service:
    name: buildkit
    state: restarted
    enabled: yes
  ignore_errors: yes