- name: Patch kube-proxy ConfigMap to set strictARP to true
  community.kubernetes.k8s:
    api_version: v1
    kind: ConfigMap
    namespace: kube-system
    name: kube-proxy
    merge_type:
      - strategic-merge
      - merge
    definition:
      data:
        config.conf: |
          kind: ConfigMap
          apiVersion: v1
          metadata:
            name: kube-proxy
            namespace: kube-system
          data:
            config.conf: |
              apiVersion: kubeproxy.config.k8s.io/v1alpha1
              kind: KubeProxyConfiguration
              mode: "iptables"
              strictARP: true
  register: patch_result

- name: Verify if the patch was applied
  debug:
    msg: "The kube-proxy ConfigMap was patched successfully."
  when: patch_result is changed