- name: Check if metallb is already installed
  community.kubernetes.helm_info:
    name: metallb
    namespace: metallb-system
  register: metallb

- name: Get the current kube-proxy ConfigMap
  shell: kubectl get configmap kube-proxy -n kube-system -o yaml
  register: current_configmap

- name: Write the current kube-proxy ConfigMap to a file
  copy:
    content: "{{ current_configmap.stdout }}"
    dest: "/tmp/current-kube-proxy-config.yaml"

- name: Update strictARP to true in the kube-proxy ConfigMap
  replace:
    path: "/tmp/current-kube-proxy-config.yaml"
    regexp: 'strictARP: false'
    replace: 'strictARP: true'
  register: update_result

- name: Apply the modified kube-proxy ConfigMap
  command: kubectl apply -f /tmp/current-kube-proxy-config.yaml -n kube-system
  when: update_result.changed

- name: Add metallb repository to Helm
  community.kubernetes.helm_repository:
    name: metallb
    repo_url: http://{{ helm_repo_ip }}/metallb
    state: present
  
- name: Install metallb Helm Chart
  community.kubernetes.helm:
    name: metallb
    chart_ref: metallb/metallb
    release_namespace: metallb-system
    create_namespace: true
  when: metallb.status is undefined or ('failed' in metallb.status)

- name: Pause for 5 seconds
  pause:
    seconds: 5

- name: Check if the metallb-system controller pod is running
  shell: kubectl get pods -n metallb-system -o jsonpath='{.items[?(@.status.phase=="Running")].metadata.name}' | grep controller
  register: result
  until: result.rc == 0
  retries: 5
  delay: 60
  ignore_errors: true

- name: Output result
  debug:
    msg: "Metallb controller pod is in running state."
  when: result.rc == 0

- name: Deploy MetalLB configuration from template
  template:
    src: metallb_config.yaml.j2
    dest: "/tmp/metallb_config.yaml"

- name: Pause for 5 seconds
  pause:
    seconds: 60

- name: Apply MetalLB configuration
  command: kubectl apply -f /tmp/metallb_config.yaml

- name: Clean up MetalLB configuration file from local
  file:
    path: "/tmp/metallb_config.yaml"
    state: absent
