- name: Check if metallb is already installed
  community.kubernetes.helm_info:
    name: metallb
    namespace: metallb-system
  register: metallb

- name: Download MetalLB manifest
  command: wget -O /tmp/metallb-native.yaml "{{ repo_url.centos }}/metallb-native.yaml"
  vars:
    version: "0.13.11"

- name: Apply MetalLB manifest
  command: kubectl apply -f /tmp/metallb-native.yaml

- name: Pause for 5 seconds
  pause:
    seconds: 5

- name: Check if the metallb-system controller pod is running
  shell: kubectl get pods -n metallb-system -o jsonpath='{.items[?(@.status.phase=="Running")].metadata.name}' | grep controller
  register: result
  until: result.rc == 0
  retries: 5
  delay: 60
  ignore_errors: true

- name: Output result
  debug:
    msg: "Metallb controller pod is in running state."
  when: result.rc == 0

- name: Deploy MetalLB configuration from template
  template:
    src: metallb_config.yaml.j2
    dest: "/tmp/metallb_config.yaml"

- name: Pause for 5 seconds
  pause:
    seconds: 60

- name: Apply MetalLB configuration
  command: kubectl apply -f /tmp/metallb_config.yaml

- name: Clean up MetalLB configuration file from local
  file:
    path: "/tmp/metallb_config.yaml"
    state: absent
