---
- name: Install Helm (CentOS & Ubuntu)
  get_url:
    url: "{{ repo_url.centos }}/helm"
    dest: "/tmp/helm"
    mode: '0777'
  when: ansible_facts['os_family'] == "RedHat"
  tags:
    - tools

- name: Install Helm (CentOS & Ubuntu)
  get_url:
    url: "{{ repo_url.ubuntu }}/helm"
    dest: "/tmp/helm"
    mode: '0777'
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - tools

- name: copy Helm
  copy:
    src: "/tmp/helm"
    dest: "/usr/local/bin"
    remote_src: yes
    mode: '0777'
  tags:
    - tools

- name: Install k9s (CentOS & Ubuntu)
  get_url:
    url: "{{ repo_url.centos }}/k9s"
    dest: "/tmp/k9s"
    mode: '0777'
  when: ansible_facts['os_family'] == "RedHat"
  tags:
    - tools
  
- name: Install k9s (CentOS & Ubuntu)
  get_url:
    url: "{{ repo_url.ubuntu}}/k9s"
    dest: "/tmp/k9s"
    mode: '0777'
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - tools

- name: copy k9s
  copy:
    src: "/tmp/k9s"
    dest: "/usr/local/bin"
    remote_src: yes
    mode: '0777'
  tags:
    - tools

- name: Add kubectl completion to .bashrc
  lineinfile:
    path: ~/.bashrc
    line: 'source <(kubectl completion bash)'
    create: yes
    state: present
  tags:
    - tools

- name: Add kubectl alias to .bashrc
  lineinfile:
    path: ~/.bashrc
    line: 'alias k=kubectl'
    create: yes
    state: present
  tags:
    - tools

- name: Add kubectl auto-completion for alias to .bashrc
  lineinfile:
    path: ~/.bashrc
    line: 'complete -o default -F __start_kubectl k'
    create: yes
    state: present
  tags:
    - tools

- name: Source the .bashrc file to apply changes
  command: bash -c "source ~/.bashrc"
  args:
    executable: /bin/bash
  tags:
    - tools

