---
- name: Restart Apache2
  systemd:
    name: apache2
    state: restarted
  when: ansible_os_family == "Debian"

- name: Restart httpd on RHEL
  service:
    name: httpd
    state: restarted
  when: ansible_os_family == "RedHat"
