---
- name: Configure sysctl for Kubernetes networking
  become: yes
  template:
    src: k8s.conf.j2
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload sysctl