---
- name: reload systemd-modules-load
  systemd:
    name: systemd-modules-load.service
    state: restarted
    enabled: true

- name: Restart Chrony service
  systemd:
    name: chronyd
    state: restarted
    enabled: true