---
- name: Set DNS servers for Ubuntu
  block:
    - name: Backup resolv.conf
      command: cp /etc/resolv.conf /etc/resolv.conf.backup
      
    - name: Set DNS servers in resolv.conf
      copy:
        content: |
          # Managed by Ansible
          nameserver {{ main_nameserver }}
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: '0644'
  tags: set_dns
  when: ansible_facts['os_family'] == "Debian"

- name: Set DNS servers for CentOS
  command: systemctl reload NetworkManager
  when: ansible_facts['os_family'] == "RedHat"
  tags: set_dns

- name: Set DNS servers for CentOS
  block:
    - name: Backup resolv.conf
      command: cp /etc/resolv.conf /etc/resolv.conf.backup
      
    - name: Set DNS servers in resolv.conf
      copy:
        content: |
          # Managed by Ansible
          nameserver {{ main_nameserver }}
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: '0644'
  when: ansible_facts['os_family'] == "RedHat"
  tags: set_dns
