---
- name: Install chrony package
  ansible.builtin.package:
    name: chrony
    state: present


- name: Check if this is the first host in the masters group
  set_fact:
    is_first_master: "{{ inventory_hostname == groups['masters'][0] }}"

- name: Configure chrony as a server on CentOS
  template:
    src: chrony_server.conf.j2
    dest: /etc/chrony.conf
  when: is_first_master and ansible_facts['os_family'] == "RedHat"
  notify: restart chronyd

- name: Configure chrony as a server on Ubuntu
  template:
    src: chrony_server.conf.j2
    dest: /etc/chrony/chrony.conf
  when: is_first_master and ansible_facts['os_family'] == "Debian"
  notify: restart chronyd

- name: Configure chrony as a client on CentOS
  template:
    src: chrony_client.conf.j2
    dest: /etc/chrony.conf
  when: not is_first_master and ansible_facts['os_family'] == "RedHat"
  notify: restart chronyd

- name: Configure chrony as a client on Ubuntu
  template:
    src: chrony_client.conf.j2
    dest: /etc/chrony/chrony.conf
  when: not is_first_master and ansible_facts['os_family'] == "Debian"
  notify: restart chronyd

- name: Ensure chronyd service is enabled and started (CentOS)
  ansible.builtin.service:
    name: chronyd
    enabled: yes
    state: started
  when: ansible_facts['os_family'] == "RedHat"
  
- name: Ensure chrony service is enabled and started (Ubuntu)
  ansible.builtin.service:
    name: chrony
    enabled: yes
    state: started
  when: ansible_facts['os_family'] == "Debian"