---
- name: Check if prometheus is already installed
  community.kubernetes.helm_info:
    name: prometheus
    namespace: monitoring
  register: prometheus_installed

- name: Add prometheus repository to Helm
  community.kubernetes.helm_repository:
    name: kube-prometheus-stack
    repo_url: http://{{ helm_repo_ip }}/kube-prometheus-stack
    state: present
  when: prometheus_installed.helm_info is undefined or prometheus_installed.helm_info.resources | length == 0

- name: Install or Upgrade prometheus Helm chart
  community.kubernetes.helm:
    name: kube-prometheus-stack
    chart_ref: kube-prometheus-stack/kube-prometheus-stack
    release_namespace: monitoring
    create_namespace: true
  when: prometheus_installed.helm_info is undefined or prometheus_installed.helm_info.resources | length == 0

- name: Pause for 5 seconds
  pause:
    seconds: 5

- name: Wait for all prometheus pods to be ready
  shell: >
    kubectl get pods -n monitoring -o custom-columns=:status.phase --no-headers| grep operator | grep -v Running | grep -v Completed || true
  register: not_running_rook_pods
  until: not_running_rook_pods.stdout == ""
  retries: 20
  delay: 60
  become: true