---
- name: Install HAProxy on Ubuntu
  apt:
    name: haproxy
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  tags: haproxy

- name: Install HAProxy on RHEL
  yum:
    name: haproxy
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"
  tags: haproxy

- name: Create HAProxy configuration directory
  file:
    path: /etc/haproxy
    state: directory
  tags: haproxy

- name: Create HAProxy error file directory
  file:
    path: /etc/haproxy/errors
    state: directory
  tags: haproxy

- name: Create HAProxy configuration file from template
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  tags: haproxy
  when: ansible_distribution == "Ubuntu"

- name: Create rhel_HAProxy configuration file from template
  template:
    src: rhel_haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  tags: haproxy
  when: ansible_os_family == "RedHat"

- name: Ensure HAProxy is started and enabled
  systemd:
    name: haproxy
    state: started
    enabled: yes
  tags: haproxy
  when: ansible_os_family == "RedHat"

- name: Ensure HAProxy is started and enabled
  systemd:
    name: haproxy
    state: restarted
    enabled: yes
  tags: haproxy
  when: ansible_distribution == "Ubuntu"

- name: Find Docker image files
  find:
    paths: "{{ item }}"
    patterns: "*.tar"
    recurse: yes
  loop: "{{ docker_image_directories }}"
  register: found_images
  ignore_errors: yes
  tags: debug

- name: Combine found image files
  set_fact:
    all_found_images: "{{ all_found_images | default([]) + item.files }}"
  loop: "{{ found_images.results }}"
  when: item is defined and item.files is defined
  tags: debug

- name: Debug all_found_images
  debug:
    var: all_found_images.path
  tags: debug

- name: Load container images
  command: "ctr images import {{ item.path }}"
  loop: "{{ all_found_images }}"
  register: load_result
  ignore_errors: yes
  tags: haproxy

- name: Get list of container images
  shell: ctr images ls -q
  register: container_images_output
  tags: push

- name: Filter images with 'cr' in the name
  shell: echo "{{ container_images_output.stdout }}" | grep cr
  register: filtered_image
  tags: push

- name: Push container images
  shell: "ctr images push {{ item }} --plain-http --max-concurrent-uploaded-layers=1"
  loop: "{{ filtered_image.stdout_lines }}"
  when: filtered_image.stdout_lines | length > 0
  register: push_results
  tags: push
  ignore_errors: true

- name: Print result of container image push
  debug:
    var: push_results
  tags: haproxy

- name: Ensure HAProxy is started and enabled
  systemd:
    name: haproxy
    state: restarted
    enabled: yes
  tags: haproxy
