---
- name: Add Helm repository for cert-manager
  community.kubernetes.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
    state: present

- name: Install cert-manager
  community.kubernetes.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    version: "{{ cert_manager_version }}"
    values: "{{ cert_manager_values }}"