---
- name: load image
  shell: ctr images import {{ load_image }}

- name: Check if Docker Registry container exists
  ansible.builtin.shell:
    cmd: "ctr tasks ls | grep -w {{ registry_name }}"
  register: ctr_ps_output
  changed_when: false
  ignore_errors: true

- name: Set container exists flag
  set_fact:
    container_exists: "{{ ctr_ps_output.stdout != '' }}"

- debug:
    msg: "Container exists: {{ container_exists }}"

- name: Create directory for Docker Registry data
  ansible.builtin.file:
    path: "{{ registry_data_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: not container_exists

- name: Create systemd unit file for registry
  template:
    src: templates/registry.service.j2
    dest: /etc/systemd/system/registry.service
    mode: '0644'

- name: Reload systemd to apply changes
  command: systemctl daemon-reload

- name: Enable registry service
  systemd:
    name: registry
    enabled: yes

- name: Start registry service
  systemd:
    name: registry
    state: started