---
- name: load image
  shell: ctr images import {{ load_image }}

- name: Check if Docker Registry container exists
  ansible.builtin.shell:
    cmd: "ctr tasks ls | grep -w {{ registry_name }}"
  register: ctr_ps_output
  changed_when: false
  ignore_errors: true

- name: Set container exists flag
  set_fact:
    container_exists: "{{ ctr_ps_output.stdout != '' }}"

- debug:
    msg: "Container exists: {{ container_exists }}"

- name: Create directory for Docker Registry data
  ansible.builtin.file:
    path: "{{ registry_data_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: not container_exists

- name: Reload systemd to apply changes
  shell: "nerdctl run -d --name registry --restart always -p 5000:5000 -v {{ registry_data_dir }}:/var/lib/registry registry:2"
  ignore_errors: true
