---
- name: Set hostname to inventory hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1.*'
    line: "127.0.1.1 {{ inventory_hostname }}"
    state: present

- name: Disable firewalld (CentOS/RHEL)
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_os_family == "RedHat"

- name: Disable SELinux (CentOS/RHEL)
  selinux:
    state: disabled
  when: ansible_os_family == "RedHat"

- name: Disable ufw (Ubuntu)
  service:
    name: ufw
    state: stopped
    enabled: no
  when: ansible_os_family == "Debian"

- name: Gather facts from all hosts
  setup:

- name: Configure /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'


- name: Ensure the modules-load.d directory exists
  file:
    path: /etc/modules-load.d
    state: directory
    mode: '0755'

- name: Add required kernel modules to load at boot
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      br_netfilter
      ip_vs
      ip_vs_rr
      ip_vs_wrr
      ip_vs_sh
      overlay
    owner: root
    group: root
    mode: '0644'
  notify: reload systemd-modules-load

- name: Load kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - br_netfilter
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - overlay


# set timezone
- name: Set timezone to Asia/Seoul
  timezone:
    name: "{{ set_timezone }}"
  tags: timezone

- name: Check the current timezone
  command: timedatectl
  register: timedatectl_output
  tags: timezone


- name: Show the current timezone
  debug:
    msg: "{{ timedatectl_output.stdout_lines }}"
  tags: timezone
