---
- name: Check if postgresql-ha is already installed
  community.kubernetes.helm_info:
    name: postgresql-ha
    namespace: runway
  register: postgresql_ha

- name: Add postgresql-ha repository to Helm
  community.kubernetes.helm_repository:
    name: postgresql-ha
    repo_url: http://{{ helm_repo_ip }}/postgresql-ha
    state: present
  when: postgresql_ha.helm_info is undefined or postgresql-ha.helm_info.resources | length == 0

- name: Debug postgresql-ha variable
  debug:
    var: postgresql_ha

- name: Install or update runway-postgresql-ha Helm chart
  community.kubernetes.helm:
    name: runway-postgresql
    chart_ref: postgresql-ha/postgresql-ha
    release_namespace: runway
    create_namespace: true
    values:
      customEnv:
      postgresql-ha:
        postgresql:
          replicaCount: "{{ postgresql_replica_count }}"

- name: Pause for 5 seconds
  pause:
    seconds: 5

- name: Wait for all runway pods to be ready
  shell: >
    kubectl get pods -n runway -o custom-columns=:status.phase --no-headers| grep postgresql | grep -v Running | grep -v Completed || true
  register: not_running_rook_pods
  until: not_running_rook_pods.stdout == ""
  retries: 20
  delay: 60
  become: true